
# html lang
language: zh-CN

# 设置 favicon
favicon: /img/favicon.ico


# 设置 rss
rss: /atom.xml


# 顶部菜单  
# 如果不需要显示某项,可以用'#'注释掉
menu:
  home: { path: /, fa: fab fa-fort-awesome}
  archive: { path: /archives/, fa: fas fa-archive}
  tag: { path: /tags/, fa: fas fa-hashtag}
#  category: { path: /category/, fa: far fa-folder-open}
  about: { path: /about/, fa: fab fa-grav}
  guestbook: { path: /guestbook/, fa: fab fa-telegram}
  friends: { path: /link/, fa: fab fa-weixin}
  说说: {path: /shuoshuo/, fa: fas fa-coffee}


# 首页显示Avatar或者Title
logo:
  method: 1
  avatar: 


# 如果 method: 1只显示座右铭；method: 2则同时显示座右铭和社交图标；method: 3只显示社交图标
subtitle_social: 
  method: 1
  subtitle:
    motto: Do what you love,love what you do.
    font-size: 1.25em
    font-color: "#84ccc9"

  social:
    Github:
      icon: fab fa-github
      url: https://github.com/a2396837
    Email:
      icon: fa fa-envelope
      url: mailto:894049579@qq.com





# 是否打开暗黑模式
todark:
  enable: true          # 是否打开暗黑模式


# 文章的相关信息
post_meta:
  page:
    date: true                    # 主页是否显示日期
    categories: true             # 主页是否显示分类
    wordcount: true             # 主页是否显示字数统计
    min2read: true             # 主页是否显示阅读时长
  post:
    date: true                # 文章页是否显示日期
    categories: true         # 文章页是否显示字分类
    wordcount: true         # 文章页是否显示字数统计
    min2read: true         # 文章页是否显示阅读时长
    

# 文章目录
toc:
  enable: true


# 文章自动摘要
auto_excerpt:
  enable: true
  length: 350


# Lazyload (图片懒加载)
# https://github.com/verlok/lazyload
lazyload:
  enable: true
  image: /img/loading.gif
  script: https://cdn.jsdelivr.net/npm/vanilla-lazyload/dist/lazyload.iife.min.js


# fancybox
fancybox:
  enable: true
  script: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@latest/dist/jquery.fancybox.min.js


# 百度自动推送
baidu_push:
  enable: false

# 谷歌分析
google_analytics:
# 百度分析
baidu_analytics: 9df80ee3a79777ffce442320dbbba26d


# Post copyright
copyright:
  enable: true
  license_text: 本博客所有文章除特别声明外，均采用许可协议 <a href="http://creativecommons.org/licenses/by-nc/4.0/">CC-BY-NC-4.0</a> 转载请注明出处！


# 文章分享
sharejs:
  enable: true
  sites: facebook,twitter,wechat,weibo,qq
  style: https://cdn.jsdelivr.net/npm/social-share.js/dist/css/share.min.css
  scripts: https://cdn.jsdelivr.net/npm/social-share.js/dist/js/social-share.min.js


# 赞助/捐献
reward:
  enable: true
  AliPayQR: /img/alipay.jpg                 # 支付宝收款码
  WeChatQR: /img/wechat.jpg                # 微信收款码
  PayPalLink: https://paypal.me                            # paypal收款链接


# 一个内置的简单404页面
page_404:
  enable: true
  subtitle: 'Oops! Page not found.'


# 备案:
ICP:
  enable: false
  link: 
  text: 
#  icon: /img/icp.png


# 全局字体可使用谷歌字体替换
googlefonts:
  font-family:
  link:


# highlight
highlight:
  enable: true
  style: https://cdn.jsdelivr.net/npm/highlight.js@10.1.1/styles/github.css
#   https://www.jsdelivr.com/package/npm/highlight.js?path=styles 找到你喜欢的代码高亮主题并替换上面


# mermaid
mermaid:
  enable: false
  script: https://cdn.jsdelivr.net/npm/mermaid@8.6.3/dist/mermaid.min.js


# MathJax
mathjax:
  enable: false
  script: https://cdn.jsdelivr.net/npm/mathjax@3.0.1/es5/tex-mml-chtml.js


# Valine 评论系统  https://valine.js.org
valine:
  enable: true # 如果使用valine，请设置改之为true
  appid: 
  appkey: 
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: Just go go # comment box placeholder
  avatar: mm # gravatar style
  guest_info: nick,mail,link # custom comment header
  pageSize: 10 # pagination size
  recordIP: false # 是否记录评论者IP
  serverURLs:
  emojiCDN: 
  enableQQ: true



# stylesheets loaded in the <head>
stylesheets:
- /css/style.css
- https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css
#- https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css
- https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@latest/dist/jquery.fancybox.min.css
- https://cdn.jsdelivr.net/gh/a2396837/CDN@latest/css/socialiconfont.css


# scripts loaded in the end of the body
scripts:
- /js/script.js
- https://cdn.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js
- https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.0.3/build/highlight.min.js
- https://cdn.jsdelivr.net/npm/highlightjs-line-numbers.js@2.7.0/dist/highlightjs-line-numbers.min.js




